name: Integration and Deploy
on:
  push:
    branches: [main]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
  deployment:
    needs: [integration]
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull skvdmt/skvdmt-back:latest
      - name: Stop container
        run: docker stop skvdmt-back || true
      - name: Remove container
        run: docker rm skvdmt-back || true
      - name: Create container
        run: docker create \
          --network=skvdmt \
          --name skvdmt-back \
          -e MODE=dev \
          -e DB_PASSWORD="$POSTGRES_PASSWORD" \
          skvdmt/skvdmt-back:latest
      - name: Make migration app folder on host if not exists
        run: mkdir -p /usr/src/migrations /usr/src/migrations/skvdmt-back
      - name: Copy migration files from image to host
        run: docker cp skvdmt-back:/usr/src/skvdmt-back/schema/. /usr/src/migrations/skvdmt-back
      - name: Run migration
        run: docker run -it --rm \
          --network=skvdmt \
          --name migration \
          -v "/usr/src/migrations/skvdmt-back:/migrations" \
          migrate/migrate:latest \
            -path /migrations \
            -database 'postgres://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD}}@db:5432/${{ vars.POSTGRES_DB }}?sslmode=disable' \
            up
      - name: Container start
        run: docker start skvdmt-back
